language: go

go:
  - 1.7

bbefore_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/alecthomas/gometalinter
- go get -u github.com/mattn/goveralls
- go get -u github.com/jteeuwen/go-bindata/...
- if ! go get -u code.google.com/p/go.tools/cmd/cover; then go get -u golang.org/x/tools/cmd/cover;fi
- export PATH=$PATH:$GOPATH/bin
- gometalinter --install --update

script:
- go test -v -covermode=count -coverprofile=coverage.out

after_success:
- gometalinter -e bindata --deadline=1000s ./...
